export { DISCOUNT_CODE_NON_APPLICABLE_ERROR, CONCURRENT_MODIFICATION_ERROR };

const DISCOUNT_CODE_NON_APPLICABLE_ERROR = 'DiscountCodeNonApplicable';
const CONCURRENT_MODIFICATION_ERROR = 'ConcurrentModification';
